name: arduinoiot
description: A new Flutter application
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  udp: ^3.0.2
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  get_ip: ^0.4.0
  flutter_local_notifications: ^1.4.0
  chat_list: ^0.0.1+21
  sleek_circular_slider: ^1.1.0
  control_pad: ^1.0.1+1
  fluttertoast: ^7.1.6
  group_radio_button: 1.0.1
  hive: 1.4.4+1
  flutter_rating_bar: 3.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/

