name: arduinoiot
description: A new Flutter application
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_core:
#   firebase_core: ^0.4.0+9
  camera: 0.7.0+4
  tflite: 1.0.4
  percent_indicator: 2.1.1+1
  flutter_swiper: 1.1.6
  image_picker: 0.6.1+10

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/yoga1.png
    - assets/images/profile-image.png
    - assets/models/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/models/yoga_classifier.tflite
    - assets/poses/
    - assets/
