// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZHq0jqunF_3UWg-aSfQkGSeVa9POuB4',
    appId: '1:148318806456:web:ecfc13296307a93ebbaf4d',
    messagingSenderId: '148318806456',
    projectId: 'vish-7b9b2',
    authDomain: 'vish-7b9b2.firebaseapp.com',
    databaseURL: 'https://vish-7b9b2.firebaseio.com',
    storageBucket: 'vish-7b9b2.appspot.com',
    measurementId: 'G-HGJW26S883',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACT02uBKOnSN1dGXSOW0eXjmEnbueUwkE',
    appId: '1:148318806456:android:f5fc67f0081d12a8bbaf4d',
    messagingSenderId: '148318806456',
    projectId: 'vish-7b9b2',
    databaseURL: 'https://vish-7b9b2.firebaseio.com',
    storageBucket: 'vish-7b9b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADgXE6FWTF6v7mtKtXGsXIlwrve9NvmUg',
    appId: '1:148318806456:ios:f3c5640cb9891c96bbaf4d',
    messagingSenderId: '148318806456',
    projectId: 'vish-7b9b2',
    databaseURL: 'https://vish-7b9b2.firebaseio.com',
    storageBucket: 'vish-7b9b2.appspot.com',
    iosBundleId: 'com.example.arduinoIotV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADgXE6FWTF6v7mtKtXGsXIlwrve9NvmUg',
    appId: '1:148318806456:ios:f3c5640cb9891c96bbaf4d',
    messagingSenderId: '148318806456',
    projectId: 'vish-7b9b2',
    databaseURL: 'https://vish-7b9b2.firebaseio.com',
    storageBucket: 'vish-7b9b2.appspot.com',
    iosBundleId: 'com.example.arduinoIotV2',
  );
}
